using UnityEngine;

public class RoomAutoBuilder : MonoBehaviour
{
    void Start()
    {
        Debug.Log("RoomAutoBuilder 실행됨!");
        BuildSimpleRoom();
    }

    public void BuildSimpleRoom()
    {
        GameObject oldRoom = GameObject.Find("AutoGeneratedRoom");

        if (oldRoom != null)
        {
            Destroy(oldRoom);
        }

        GameObject roomRoot = new GameObject("AutoGeneratedRoom");

        Material floorMat = CreateMat("FloorMat", new Color(0.55f, 0.50f, 0.44f));
        Material wallMat = CreateMat("WallMat", new Color(0.78f, 0.72f, 0.62f));
        Material bedMat = CreateMat("BedMat", new Color(0.30f, 0.55f, 0.90f));
        Material woodMat = CreateMat("WoodMat", new Color(0.42f, 0.25f, 0.13f));
        Material chairMat = CreateMat("ChairMat", new Color(0.18f, 0.18f, 0.18f));
        Material doorMat = CreateMat("DoorFrameMat", new Color(0.30f, 0.18f, 0.08f));

        // 바닥
        CreateCube("Floor", new Vector3(0, -0.05f, 0), new Vector3(10, 0.1f, 10), floorMat, roomRoot.transform);

        // 벽 3개
        CreateCube("BackWall", new Vector3(0, 2.5f, 5), new Vector3(10, 5, 0.2f), wallMat, roomRoot.transform);
        CreateCube("LeftWall", new Vector3(-5, 2.5f, 0), new Vector3(0.2f, 5, 10), wallMat, roomRoot.transform);
        CreateCube("RightWall", new Vector3(5, 2.5f, 0), new Vector3(0.2f, 5, 10), wallMat, roomRoot.transform);

        // 앞쪽 벽: 가운데 문 공간 비우고 양쪽 벽 + 위쪽 벽 생성
        CreateCube("FrontWall_Left", new Vector3(-3.65f, 2.5f, -5), new Vector3(2.7f, 5, 0.2f), wallMat, roomRoot.transform);
        CreateCube("FrontWall_Right", new Vector3(3.65f, 2.5f, -5), new Vector3(2.7f, 5, 0.2f), wallMat, roomRoot.transform);
        CreateCube("FrontWall_Top", new Vector3(0, 4.15f, -5), new Vector3(4.6f, 1.7f, 0.2f), wallMat, roomRoot.transform);

        // 문틀
        CreateCube("DoorFrame_Left", new Vector3(-1.25f, 1.5f, -5.08f), new Vector3(0.18f, 3.0f, 0.25f), doorMat, roomRoot.transform);
        CreateCube("DoorFrame_Right", new Vector3(1.25f, 1.5f, -5.08f), new Vector3(0.18f, 3.0f, 0.25f), doorMat, roomRoot.transform);
        CreateCube("DoorFrame_Top", new Vector3(0, 3.05f, -5.08f), new Vector3(2.7f, 0.18f, 0.25f), doorMat, roomRoot.transform);

        // 문 위치 표시용 바닥 발판
        CreateCube("Door_Threshold", new Vector3(0, 0.03f, -4.55f), new Vector3(2.4f, 0.08f, 0.9f), doorMat, roomRoot.transform);

        // 침대
        CreateCube("Bed_Base", new Vector3(-3.1f, 0.35f, 2.4f), new Vector3(2.5f, 0.5f, 3.2f), bedMat, roomRoot.transform);
        CreateCube("Bed_Pillow", new Vector3(-3.1f, 0.8f, 3.65f), new Vector3(2.0f, 0.35f, 0.6f), wallMat, roomRoot.transform);

        // 책상
        CreateCube("Desk_Top", new Vector3(2.9f, 1.0f, 2.4f), new Vector3(2.4f, 0.2f, 1.2f), woodMat, roomRoot.transform);
        CreateCube("Desk_Leg1", new Vector3(1.9f, 0.5f, 1.9f), new Vector3(0.18f, 1.0f, 0.18f), woodMat, roomRoot.transform);
        CreateCube("Desk_Leg2", new Vector3(3.9f, 0.5f, 1.9f), new Vector3(0.18f, 1.0f, 0.18f), woodMat, roomRoot.transform);
        CreateCube("Desk_Leg3", new Vector3(1.9f, 0.5f, 2.9f), new Vector3(0.18f, 1.0f, 0.18f), woodMat, roomRoot.transform);
        CreateCube("Desk_Leg4", new Vector3(3.9f, 0.5f, 2.9f), new Vector3(0.18f, 1.0f, 0.18f), woodMat, roomRoot.transform);

        // 의자
        CreateCube("Chair_Seat", new Vector3(2.9f, 0.55f, 0.8f), new Vector3(1.1f, 0.2f, 1.1f), chairMat, roomRoot.transform);
        CreateCube("Chair_Back", new Vector3(2.9f, 1.2f, 0.25f), new Vector3(1.1f, 1.2f, 0.2f), chairMat, roomRoot.transform);
        CreateCube("Chair_Leg1", new Vector3(2.45f, 0.25f, 0.35f), new Vector3(0.15f, 0.5f, 0.15f), chairMat, roomRoot.transform);
        CreateCube("Chair_Leg2", new Vector3(3.35f, 0.25f, 0.35f), new Vector3(0.15f, 0.5f, 0.15f), chairMat, roomRoot.transform);
        CreateCube("Chair_Leg3", new Vector3(2.45f, 0.25f, 1.25f), new Vector3(0.15f, 0.5f, 0.15f), chairMat, roomRoot.transform);
        CreateCube("Chair_Leg4", new Vector3(3.35f, 0.25f, 1.25f), new Vector3(0.15f, 0.5f, 0.15f), chairMat, roomRoot.transform);

        // 조명
        GameObject lightObj = new GameObject("Room_Light");
        lightObj.transform.parent = roomRoot.transform;
        lightObj.transform.position = new Vector3(0, 4.5f, 0);

        Light light = lightObj.AddComponent<Light>();
        light.type = LightType.Point;
        light.intensity = 2.5f;
        light.range = 12f;

        // SpawnPoint
        GameObject spawn = new GameObject("SpawnPoint");
        spawn.transform.parent = roomRoot.transform;
        spawn.transform.position = new Vector3(0, 1.0f, -2.6f);
        spawn.transform.rotation = Quaternion.Euler(0, 180, 0);
        spawn.tag = "SpawnPoint";

        // ExitTrigger: 문 앞에 위치
        GameObject exit = new GameObject("ExitTrigger");
        exit.transform.parent = roomRoot.transform;
        exit.transform.position = new Vector3(0, 1.5f, -4.65f);

        BoxCollider exitCol = exit.AddComponent<BoxCollider>();
        exitCol.isTrigger = true;
        exitCol.size = new Vector3(4.0f, 4.0f, 2.0f);

        exit.AddComponent<ExitHouseTrigger>();

        Debug.Log("방 자동 생성 완료! 4면 벽 + 문 + ExitTrigger 생성됨");
    }

    private GameObject CreateCube(string name, Vector3 position, Vector3 scale, Material mat, Transform parent)
    {
        GameObject obj = GameObject.CreatePrimitive(PrimitiveType.Cube);
        obj.name = name;
        obj.transform.parent = parent;
        obj.transform.position = position;
        obj.transform.localScale = scale;

        Renderer renderer = obj.GetComponent<Renderer>();

        if (renderer != null)
        {
            renderer.material = mat;
        }

        return obj;
    }

    private Material CreateMat(string name, Color color)
    {
        Shader shader = Shader.Find("Universal Render Pipeline/Lit");

        if (shader == null)
        {
            shader = Shader.Find("Standard");
        }

        Material mat = new Material(shader);
        mat.name = name;
        mat.color = color;

        return mat;
    }
}